language: ruby
rvm:
    - 2.0.0
    - 2.1.8
    - 2.2.4
    - 2.3.1

gemfile: gemfiles/flipper-consul.gemfile

env:
  - FLIPPER_VERSION: 0.9.2
  - FLIPPER_VERSION: 0.8.0
  - FLIPPER_VERSION: 0.7.5

before_script:
    - wget 'https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_linux_amd64.zip' --output-document=consul.zip
    - unzip 'consul.zip'
    - ./consul --version

script:
    - ./consul agent -server -bootstrap-expect 1 -data-dir /tmp/consul &
